### ISSUE TITLE
Custom folder for local tips

### ISSUE THREAD

**Issue by belibug** [deadlydog/PowerShell.tiPS#38]
Excellent and really well built project. It has huge potential and would be perfect drop-in replacement for `flashcards` like programs.

But not all tips are for everyone, and not all tips are about PowerShell. It would be great if you can create a custom directory where user can store his/her own tips which are local and on-device. Allowing one to cycle through all the tips (both hosted here and local)

This way tiPS wont be limited to PowerShell or hosted only tips.

We can brainstorm and I will be happy to contribute.

**Comment by deadlydog** [comment]
That is an interesting idea that I hadn't considered. Kind of like a very simple version of [Anki](https://apps.ankiweb.net/). I'm not sure that's something that I would implement as part of this specific module, or instead something that could be forked into its own new repo. Kind of like a "reminders" module where you could leave notes (tips) for yourself. I'll have to give it some more thought on if I want that functionality as part of this module or not. If you have any other comments or I'm missing something, let me know 🙂

**Comment by deadlydog** [comment]
After further consideration, while I like the idea, I don't think it helps drive this module's main objective of "PowerShell tips delivered straight to your terminal". If you store your own non-PowerShell tips locally, then the cmdlet names would not make sense anymore (e.g. Write-PowerShellTip may write something not PowerShell related). If you are storing PowerShell related tips locally, then why not share them with the rest of the world by contributing them to the module.

Feel free to fork this repo and come up with a new module for storing custom notes/tips, but I don't think this feature is a good fit for this module so I am going to close this issue. If you think there is something I am missing, let me know. I appreciate you taking time to make the suggestion and provide feedback 🙂

**Comment by belibug** [comment]
That makes sense. I appreciate your detailed response.
